api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/User/Entity']
    title: '%env(PROJECT_NAME)%'
    version: 0.0.0
    # Enable the Varnish integration
    http_cache:
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
    enable_fos_user: true
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header