api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: '%env(PROJECT_NAME)%'
    version: 0.0.0
    # Enable the Varnish integration
    http_cache:
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
