imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      deduplicated
        deduplicated:
            type:    deduplication
            handler: swift
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
        swift:
            type:       swift_mailer
            from_email: '%project_name_slug%@whatson-web.com'
            to_email:   'logs@whatson-web.com'
            subject:    '%project_name% - Erreur détectée : %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
